services:

  # Servicio de inferencia con GPU (Python + FastAPI)
  cuda-service:
    build: ./gpu-service
    ports:
      - "8000:8000"       # esta exponiendo el puerto 8000 para FastAPI
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - upsglam-net

  # Backend principal (Java + Spring Boot)
  backend:
    build: ./backend      # requiere Dockerfile en ./backend 
    ports:
      - "8080:8080"
    env_file: .env        # carga todas las variables de .env
    environment:
      CUDA_SERVICE_URL: http://cuda-service:8000   # hostname interno de Docker
    depends_on:
      - cuda-service
    networks:
      - upsglam-net

# es la red interna para que los servicios se comuniquen entre sí
networks:
  upsglam-net:
    driver: bridge
